[package]
name = "stoozey/enumz"
description = "Enum system"
version = "2.3.0"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"